//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1497510418_dollar_currency__money_recycle {
            get {
                object obj = ResourceManager.GetObject("1497510418_dollar-currency-_money-recycle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Add_File_40px {
            get {
                object obj = ResourceManager.GetObject("Add File_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap American_Indians_Seminole_white_20px {
            get {
                object obj = ResourceManager.GetObject("American Indians Seminole_white_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap American_Indians_Seminole_white_40px {
            get {
                object obj = ResourceManager.GetObject("American Indians Seminole_white_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap American_Indians_Seminole_white_50px {
            get {
                object obj = ResourceManager.GetObject("American Indians Seminole_white_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Cash_Register_40px {
            get {
                object obj = ResourceManager.GetObject("Cash Register_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Circled_User_Male_40px {
            get {
                object obj = ResourceManager.GetObject("Circled User Male_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Close_Window_52px {
            get {
                object obj = ResourceManager.GetObject("Close Window_52px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Coins_48px {
            get {
                object obj = ResourceManager.GetObject("Coins_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Construction_Worker_40px {
            get {
                object obj = ResourceManager.GetObject("Construction Worker_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Crystal_40px {
            get {
                object obj = ResourceManager.GetObject("Crystal_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Documents_40px {
            get {
                object obj = ResourceManager.GetObject("Documents_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Hangar_40px {
            get {
                object obj = ResourceManager.GetObject("Hangar_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Hangar_64px {
            get {
                object obj = ResourceManager.GetObject("Hangar_64px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Inca_Art {
            get {
                object obj = ResourceManager.GetObject("Inca Art", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Maximize_Window_64px {
            get {
                object obj = ResourceManager.GetObject("Maximize Window_64px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Menu_64px {
            get {
                object obj = ResourceManager.GetObject("Menu_64px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Microsoft_Excel_40px {
            get {
                object obj = ResourceManager.GetObject("Microsoft Excel_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Minimize_Window_52px {
            get {
                object obj = ResourceManager.GetObject("Minimize Window_52px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mortar_and_Pestle_40px {
            get {
                object obj = ResourceManager.GetObject("Mortar and Pestle_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Overtime_40px {
            get {
                object obj = ResourceManager.GetObject("Overtime_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pdf {
            get {
                object obj = ResourceManager.GetObject("pdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Product_40px {
            get {
                object obj = ResourceManager.GetObject("Product_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Reviewer_Male_40px {
            get {
                object obj = ResourceManager.GetObject("Reviewer Male_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sales_Performance_64px {
            get {
                object obj = ResourceManager.GetObject("Sales Performance_64px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search_16 {
            get {
                object obj = ResourceManager.GetObject("Search_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Settings_48px {
            get {
                object obj = ResourceManager.GetObject("Settings_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Shopping_Cart_40px {
            get {
                object obj = ResourceManager.GetObject("Shopping Cart_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Shopping_Cart_52px {
            get {
                object obj = ResourceManager.GetObject("Shopping Cart_52px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tumi {
            get {
                object obj = ResourceManager.GetObject("Tumi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Undo_40px {
            get {
                object obj = ResourceManager.GetObject("Undo_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap User_Group_Man_Man_52px {
            get {
                object obj = ResourceManager.GetObject("User Group Man Man_52px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Webcam_Man_48px {
            get {
                object obj = ResourceManager.GetObject("Webcam Man_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Workers_Male_52px {
            get {
                object obj = ResourceManager.GetObject("Workers Male_52px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
